/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);

export type FileRoutesByFullPath = {
    "/": typeof IndexRoute;
};
export type FileRoutesByTo = {
    "/": typeof IndexRoute;
};
export type FileRoutesById = {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
};
export type FileRouteTypes = {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/";
    fileRoutesByTo: FileRoutesByTo;
    to: "/";
    id: "__root__" | "/";
    fileRoutesById: FileRoutesById;
};
export type RootRouteChildren = {
    IndexRoute: typeof IndexRoute;
};

declare module "@tanstack/react-router" {
    type FileRoutesByPath = {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
    };
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
    type Register = {
        ssr: true;
        router: Awaited<ReturnType<typeof getRouter>>;
    };
}
